name: bld-ci

on: [push, pull_request, workflow_dispatch]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 20 ]

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Run Tests
        run: ./bld download compile detekt test

      - name: Build Documentation
        run: |
          ./bld javadoc
          ./bld dokka-html
          ./bld dokka-gfm
          ./bld dokka-jekyll